#!/bin/bash

# Continue inserting the remaining 19 styles

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (2, '2025-06-23 12:00:00', 'High-end executive portrait with power pose and luxury office background', 1, 'executive', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual clothing, unprofessional setting', 'High-end executive portrait of a {gender}, power pose, elegant business suit, luxury office background, natural light, serious expression, premium look', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (3, '2025-06-23 12:00:00', 'Friendly consultant portrait in smart-casual attire with approachable expression', 1, 'consultant', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, overly formal attire, intimidating expression', 'Portrait of a friendly {gender} consultant in semi-formal smart-casual attire, clean background, approachable expression, modern professional tone', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (4, '2025-06-23 12:00:00', 'Professional LinkedIn-style headshot with confident and warm expression', 1, 'linkedin', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, full body shot, distracting background', 'Professional LinkedIn-style headshot of a {gender}, neutral background, confident and warm smile, clean business-casual attire, high clarity', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (5, '2025-06-23 12:00:00', 'Formal lawyer portrait in courtroom or law office setting', 1, 'legal', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual setting, inappropriate attire', 'Formal portrait of a {gender} lawyer in courtroom or law office, dark tailored suit, serious expression, soft shadows, bookshelf or columns in background', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (6, '2025-06-23 12:00:00', 'Healthcare professional portrait with lab coat and trustworthy expression', 1, 'medical', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, inappropriate medical setting', 'Portrait of a {gender} healthcare professional in lab coat, stethoscope, hospital or clinic background, calm and trustworthy expression, soft light', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (7, '2025-06-23 12:00:00', 'Intellectual author portrait with bookshelves or writing desk background', 1, 'author', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation', 'Intellectual portrait of a {gender} with bookshelves or writing desk in the background, warm ambient lighting, thoughtful gaze, creative professional styling', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (8, '2025-06-23 12:00:00', 'Modern startup founder portrait in co-working space with confident energy', 1, 'entrepreneur', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, outdated office, traditional formal attire', 'Modern portrait of a {gender} startup founder in a co-working space or minimalist office, tech-savvy outfit, confident energy, natural lighting', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (9, '2025-06-23 12:00:00', 'Casual-smart startup founder with t-shirt and blazer combination', 1, 'startup', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, overly formal suit', 'Casual-smart headshot of a {gender} in a t-shirt and blazer, clean tech-style background, bright lighting, relaxed smile, startup founder vibe', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (10, '2025-06-23 12:00:00', 'Tech professional portrait with laptop or code in background', 1, 'tech professional', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, outdated technology', 'Portrait of a {gender} tech professional in modern outfit, with a laptop or code in background, neutral tones, focused expression, digital workspace', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (11, '2025-06-23 12:00:00', 'Trendy social media influencer portrait with engaging eye contact', 1, 'influencer', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, overly professional attire', 'Trendy portrait of a {gender} social media influencer with engaging eye contact, soft lighting, fashionable outfit, blurred background, Instagram vibe', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (12, '2025-06-23 12:00:00', 'Outdoor lifestyle portrait of remote worker with laptop in natural setting', 1, 'digital nomad', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, indoor office setting', 'Outdoor lifestyle portrait of a {gender} remote worker, natural lighting, beach or mountain cafe background, laptop in view, relaxed expression', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (13, '2025-06-23 12:00:00', 'Colorful and dynamic artist portrait with creative studio background', 1, 'creative', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, boring background, corporate attire', 'Colorful and dynamic portrait of a {gender} artist or creative, expressive pose, vibrant lighting, creative studio background, bold composition', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (14, '2025-06-23 12:00:00', 'Natural lifestyle photo in everyday clothing with warm lighting', 1, 'casual', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, formal business attire', 'Natural lifestyle photo of a {gender} in everyday clothing, warm lighting, soft expression, home or park background, candid feel', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (15, '2025-06-23 12:00:00', 'Fine art portrait with dramatic lighting and stylized clothing', 1, 'artistic', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, plain background, conventional lighting', 'Fine art portrait of a {gender} in dramatic lighting, stylized clothing, moody background, painterly composition, thoughtful gaze', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (16, '2025-06-23 12:00:00', 'Street-style portrait with gritty city background and edgy aesthetic', 1, 'edgy/urban', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, clean corporate setting, formal attire', 'Street-style portrait of a {gender}, gritty city background, bold outfit, high contrast lighting, strong pose, edgy aesthetic', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (17, '2025-06-23 12:00:00', 'Fashion-inspired glamorous portrait with studio lighting and luxury feel', 1, 'glamour', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual everyday clothing', 'Fashion-inspired portrait of a {gender} in glamorous makeup and clothing, studio lighting, soft glow effect, luxury editorial feel', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (18, '2025-06-23 12:00:00', 'Scholar portrait with books or chalkboard in academic setting', 1, 'academic', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation', 'Portrait of a {gender} scholar with books or chalkboard in background, glasses, thoughtful expression, classic academic setting and lighting', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (19, '2025-06-23 12:00:00', 'Athletic portrait in workout gear with energetic expression', 1, 'fitness', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, formal business attire', 'Athletic portrait of a {gender} in workout gear, gym or outdoor fitness location, strong pose, energetic expression, high contrast lighting', '2025-06-23 12:00:00');"

sqlite3 aiprofilemaker.db "INSERT INTO Styles (Id, CreatedAt, Description, IsActive, Name, NegativePromptTemplate, PromptTemplate, UpdatedAt) VALUES (20, '2025-06-23 12:00:00', 'Serene portrait in natural light with peaceful spiritual elements', 1, 'spiritual', 'deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, busy commercial setting', 'Serene portrait of a {gender} in natural light, peaceful outdoor or temple-like setting, soft expression, spiritual elements like beads or robes', '2025-06-23 12:00:00');"

echo "All 20 styles inserted successfully!"