// <auto-generated />
using System;
using AI.ProfilePhotoMaker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AI.ProfilePhotoMaker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250904200128_RestoreDigitalNativeStyle")]
    partial class RestoreDigitalNativeStyle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration only updates existing data, no model changes required
            // Model snapshot remains the same as previous migration
        }
    }
}