// <auto-generated />
using System;
using AI.ProfilePhotoMaker.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AI.ProfilePhotoMaker.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250807161356_InitialSQLite")]
    partial class InitialSQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.16");

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.CreditPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BonusCredits")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePriceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_CreditPackages_Name_Unique");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("IX_CreditPackages_IsActive_DisplayOrder");

                    b.ToTable("CreditPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonusCredits = 0,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6373),
                            Credits = 50,
                            Description = "Perfect for trying out custom training and styled generations",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Starter Pack",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 2,
                            BonusCredits = 30,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6376),
                            Credits = 120,
                            Description = "Most popular - great for professionals",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Professional Pack",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            BonusCredits = 100,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6379),
                            Credits = 300,
                            Description = "Best value for content creators and businesses",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Studio Pack",
                            Price = 39.99m
                        });
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.CreditPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CreditsAwarded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("PurchaseDate")
                        .HasDatabaseName("IX_CreditPurchases_PurchaseDate");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_CreditPurchases_UserId");

                    b.ToTable("CreditPurchases");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.ModelCreationRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingTrainingRequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplicateModelId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrainedModelVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingImageZipUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ModelCreationRequests_CreatedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ModelCreationRequests_Status");

                    b.ToTable("ModelCreationRequests");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PaymentTransactions_CreatedAt");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_PaymentTransactions_UserId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.ProcessedImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOriginalUpload")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessedImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDeletionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ProcessedImages_CreatedAt");

                    b.HasIndex("ProcessedImageUrl")
                        .IsUnique()
                        .HasDatabaseName("IX_ProcessedImages_ProcessedImageUrl_Unique");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("IX_ProcessedImages_UserProfileId");

                    b.ToTable("ProcessedImages");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.Style", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NegativePromptTemplate")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptTemplate")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Styles_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Styles_Name_Unique");

                    b.HasIndex("IsActive", "Name")
                        .HasDatabaseName("IX_Styles_IsActive_Name");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6559),
                            Description = "Professional corporate headshot style",
                            IsActive = true,
                            Name = "corporate",
                            NegativePromptTemplate = "casual clothes, blurred, low quality, unprofessional",
                            PromptTemplate = "professional corporate headshot, business attire, clean background, confident expression, high-quality photography",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6559)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6562),
                            Description = "Executive leadership portrait",
                            IsActive = true,
                            Name = "executive",
                            NegativePromptTemplate = "casual, informal, poor lighting, unprofessional",
                            PromptTemplate = "executive portrait, professional leadership style, formal business attire, authoritative presence, studio lighting",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6562)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6564),
                            Description = "Professional consultant style",
                            IsActive = true,
                            Name = "consultant",
                            NegativePromptTemplate = "too casual, unprofessional, blurred",
                            PromptTemplate = "professional consultant portrait, business consulting style, smart casual attire, approachable yet professional",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6564)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6566),
                            Description = "LinkedIn professional networking",
                            IsActive = true,
                            Name = "linkedin",
                            NegativePromptTemplate = "casual clothes, distracting background, unprofessional",
                            PromptTemplate = "linkedin profile photo, professional networking style, business attire, friendly professional expression, clean background",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6567)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6569),
                            Description = "Legal professional portrait",
                            IsActive = true,
                            Name = "legal",
                            NegativePromptTemplate = "casual, informal, unprofessional",
                            PromptTemplate = "legal professional portrait, formal business attire, trustworthy appearance, professional law office style",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6570)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6572),
                            Description = "Healthcare professional style",
                            IsActive = true,
                            Name = "medical",
                            NegativePromptTemplate = "casual clothes, unprofessional, poor quality",
                            PromptTemplate = "medical professional portrait, healthcare style, professional medical attire, trustworthy healthcare provider appearance",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6573)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6575),
                            Description = "Author and writer portrait",
                            IsActive = true,
                            Name = "author",
                            NegativePromptTemplate = "unprofessional, distracting elements, poor composition",
                            PromptTemplate = "author portrait, writer style, creative professional appearance, literary aesthetic, thoughtful expression",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6575)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6577),
                            Description = "Entrepreneurial business style",
                            IsActive = true,
                            Name = "entrepreneur",
                            NegativePromptTemplate = "formal corporate look, traditional, static pose",
                            PromptTemplate = "entrepreneur portrait, innovative business leader style, modern professional attire, dynamic confident expression",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6577)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6579),
                            Description = "Startup professional style",
                            IsActive = true,
                            Name = "startup",
                            NegativePromptTemplate = "overly formal, traditional corporate, stiff pose",
                            PromptTemplate = "startup professional portrait, innovative tech style, modern casual business attire, entrepreneurial spirit",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6580)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6582),
                            Description = "Technology professional style",
                            IsActive = true,
                            Name = "tech-professional",
                            NegativePromptTemplate = "overly formal, outdated style, unprofessional",
                            PromptTemplate = "tech professional portrait, modern technology industry style, smart casual tech attire, innovative professional look",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6582)
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6584),
                            Description = "Social media influencer style",
                            IsActive = true,
                            Name = "influencer",
                            NegativePromptTemplate = "overly formal, corporate look, boring expression",
                            PromptTemplate = "social media influencer portrait, engaging personality style, trendy professional appearance, charismatic expression",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6584)
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6586),
                            Description = "Digital nomad professional",
                            IsActive = true,
                            Name = "digital-nomad",
                            NegativePromptTemplate = "formal office attire, traditional corporate, static background",
                            PromptTemplate = "digital nomad portrait, remote work professional style, casual modern attire, location-independent professional",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6586)
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6588),
                            Description = "Creative professional style",
                            IsActive = true,
                            Name = "creative",
                            NegativePromptTemplate = "corporate formal, traditional business, boring conventional look",
                            PromptTemplate = "creative professional portrait, artistic style, expressive creative look, innovative artistic appearance",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6589)
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6591),
                            Description = "Casual professional style",
                            IsActive = true,
                            Name = "casual",
                            NegativePromptTemplate = "overly formal, stiff corporate, too dressy",
                            PromptTemplate = "casual professional portrait, relaxed business style, smart casual attire, approachable friendly appearance",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6591)
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6593),
                            Description = "Artistic creative portrait",
                            IsActive = true,
                            Name = "artistic",
                            NegativePromptTemplate = "corporate business, formal attire, conventional look",
                            PromptTemplate = "artistic portrait, creative artistic style, expressive artistic look, bohemian creative appearance",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6593)
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6595),
                            Description = "Edgy urban style",
                            IsActive = true,
                            Name = "edgy-urban",
                            NegativePromptTemplate = "conservative formal, traditional business, bland conventional",
                            PromptTemplate = "edgy urban portrait, modern urban style, contemporary city fashion, bold confident expression",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6595)
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6597),
                            Description = "Glamour portrait style",
                            IsActive = true,
                            Name = "glamour",
                            NegativePromptTemplate = "casual simple, plain appearance, understated look",
                            PromptTemplate = "glamour portrait, elegant sophisticated style, polished glamorous appearance, high-end fashion aesthetic",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6598)
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6599),
                            Description = "Academic professional style",
                            IsActive = true,
                            Name = "academic",
                            NegativePromptTemplate = "casual informal, unprofessional, non-academic",
                            PromptTemplate = "academic portrait, scholarly professional style, intellectual appearance, educational professional look",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6601)
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6602),
                            Description = "Fitness professional style",
                            IsActive = true,
                            Name = "fitness",
                            NegativePromptTemplate = "sedentary look, unhealthy appearance, low energy",
                            PromptTemplate = "fitness professional portrait, athletic style, health and wellness appearance, energetic confident look",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6603)
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6605),
                            Description = "Spiritual wellness style",
                            IsActive = true,
                            Name = "spiritual",
                            NegativePromptTemplate = "materialistic look, stressed appearance, conventional business",
                            PromptTemplate = "spiritual portrait, wellness style, mindful peaceful appearance, holistic health aesthetic",
                            UpdatedAt = new DateTime(2025, 8, 7, 16, 13, 56, 332, DateTimeKind.Utc).AddTicks(6605)
                        });
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CancelAtPeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalCustomerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSubscriptionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastPaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextBillingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Subscriptions_UserId");

                    b.HasIndex("StartDate", "EndDate")
                        .HasDatabaseName("IX_Subscriptions_DateRange");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.SubscriptionPlan", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CanBatchGenerate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanTrainCustomModels")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HighResolutionOutput")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImagesPerMonth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStylesAccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTrainingImages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("StripePriceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StripeProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.UsageLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreditsCost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreditsRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_UsageLogs_CreatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UsageLogs_UserId");

                    b.ToTable("UsageLogs");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Credits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastCreditReset")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModelSyncCheck")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PurchasedCredits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StyleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriptionTier")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StyleId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserProfiles_UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.UserStyleSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SelectedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StyleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StyleId")
                        .HasDatabaseName("IX_UserStyleSelections_StyleId");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("IX_UserStyleSelections_UserProfileId");

                    b.HasIndex("UserProfileId", "StyleId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserStyleSelections_UserProfile_Style_Unique");

                    b.ToTable("UserStyleSelections");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.CreditPurchase", b =>
                {
                    b.HasOne("AI.ProfilePhotoMaker.API.Models.CreditPackage", "Package")
                        .WithMany("Purchases")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.ProfilePhotoMaker.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.PaymentTransaction", b =>
                {
                    b.HasOne("AI.ProfilePhotoMaker.API.Models.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("AI.ProfilePhotoMaker.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.ProcessedImage", b =>
                {
                    b.HasOne("AI.ProfilePhotoMaker.API.Models.UserProfile", "UserProfile")
                        .WithMany("ProcessedImages")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.Subscription", b =>
                {
                    b.HasOne("AI.ProfilePhotoMaker.API.Models.SubscriptionPlan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.ProfilePhotoMaker.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.UsageLog", b =>
                {
                    b.HasOne("AI.ProfilePhotoMaker.API.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.ProfilePhotoMaker.API.Models.UserProfile", null)
                        .WithMany("UsageLogs")
                        .HasForeignKey("UserId")
                        .HasPrincipalKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.UserProfile", b =>
                {
                    b.HasOne("AI.ProfilePhotoMaker.API.Models.Style", null)
                        .WithMany("UserProfiles")
                        .HasForeignKey("StyleId");

                    b.HasOne("AI.ProfilePhotoMaker.API.Models.ApplicationUser", "User")
                        .WithOne()
                        .HasForeignKey("AI.ProfilePhotoMaker.API.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.UserStyleSelection", b =>
                {
                    b.HasOne("AI.ProfilePhotoMaker.API.Models.Style", "Style")
                        .WithMany()
                        .HasForeignKey("StyleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.ProfilePhotoMaker.API.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Style");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AI.ProfilePhotoMaker.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AI.ProfilePhotoMaker.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI.ProfilePhotoMaker.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AI.ProfilePhotoMaker.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.CreditPackage", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.Style", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("AI.ProfilePhotoMaker.API.Models.UserProfile", b =>
                {
                    b.Navigation("ProcessedImages");

                    b.Navigation("UsageLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
