using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace AI.ProfilePhotoMaker.API.Migrations
{
    /// <inheritdoc />
    public partial class UpdateStylesWithCustomSet : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Remove all existing styles
            migrationBuilder.DeleteData(
                table: "Styles",
                keyColumn: "Id",
                keyValues: new object[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 });

            // Insert new custom styles
            migrationBuilder.InsertData(
                table: "Styles",
                columns: new[] { "Id", "CreatedAt", "Description", "IsActive", "Name", "NegativePromptTemplate", "PromptTemplate", "UpdatedAt" },
                values: new object[,]
                {
                    // Professional & Career Styles
                    { 1, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Professional studio portrait in formal business attire with clean background", true, "corporate", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual clothing, inappropriate attire", "Professional studio portrait of a {gender} in formal business attire, clean background, confident expression, corporate office lighting, sharp focus", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 2, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "High-end executive portrait with power pose and luxury office background", true, "executive", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual clothing, unprofessional setting", "High-end executive portrait of a {gender}, power pose, elegant business suit, luxury office background, natural light, serious expression, premium look", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 3, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Friendly consultant portrait in smart-casual attire with approachable expression", true, "consultant", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, overly formal attire, intimidating expression", "Portrait of a friendly {gender} consultant in semi-formal smart-casual attire, clean background, approachable expression, modern professional tone", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 4, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Professional LinkedIn-style headshot with confident and warm expression", true, "linkedin", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, full body shot, distracting background", "Professional LinkedIn-style headshot of a {gender}, neutral background, confident and warm smile, clean business-casual attire, high clarity", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 5, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Formal lawyer portrait in courtroom or law office setting", true, "legal", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual setting, inappropriate attire", "Formal portrait of a {gender} lawyer in courtroom or law office, dark tailored suit, serious expression, soft shadows, bookshelf or columns in background", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 6, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Healthcare professional portrait with lab coat and trustworthy expression", true, "medical", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, inappropriate medical setting", "Portrait of a {gender} healthcare professional in lab coat, stethoscope, hospital or clinic background, calm and trustworthy expression, soft light", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 7, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Intellectual author portrait with bookshelves or writing desk background", true, "author", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation", "Intellectual portrait of a {gender} with bookshelves or writing desk in the background, warm ambient lighting, thoughtful gaze, creative professional styling", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    
                    // Modern Entrepreneur & Tech Styles
                    { 8, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Modern startup founder portrait in co-working space with confident energy", true, "entrepreneur", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, outdated office, traditional formal attire", "Modern portrait of a {gender} startup founder in a co-working space or minimalist office, tech-savvy outfit, confident energy, natural lighting", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 9, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Casual-smart startup founder with t-shirt and blazer combination", true, "startup", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, overly formal suit", "Casual-smart headshot of a {gender} in a t-shirt and blazer, clean tech-style background, bright lighting, relaxed smile, startup founder vibe", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 10, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Tech professional portrait with laptop or code in background", true, "tech professional", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, outdated technology", "Portrait of a {gender} tech professional in modern outfit, with a laptop or code in background, neutral tones, focused expression, digital workspace", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 11, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Trendy social media influencer portrait with engaging eye contact", true, "influencer", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, overly professional attire", "Trendy portrait of a {gender} social media influencer with engaging eye contact, soft lighting, fashionable outfit, blurred background, Instagram vibe", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 12, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Outdoor lifestyle portrait of remote worker with laptop in natural setting", true, "digital nomad", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, indoor office setting", "Outdoor lifestyle portrait of a {gender} remote worker, natural lighting, beach or mountain cafe background, laptop in view, relaxed expression", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    
                    // Creative, Lifestyle & Expressive Styles
                    { 13, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Colorful and dynamic artist portrait with creative studio background", true, "creative", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, boring background, corporate attire", "Colorful and dynamic portrait of a {gender} artist or creative, expressive pose, vibrant lighting, creative studio background, bold composition", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 14, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Natural lifestyle photo in everyday clothing with warm lighting", true, "casual", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, formal business attire", "Natural lifestyle photo of a {gender} in everyday clothing, warm lighting, soft expression, home or park background, candid feel", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 15, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Fine art portrait with dramatic lighting and stylized clothing", true, "artistic", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, plain background, conventional lighting", "Fine art portrait of a {gender} in dramatic lighting, stylized clothing, moody background, painterly composition, thoughtful gaze", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 16, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Street-style portrait with gritty city background and edgy aesthetic", true, "edgy/urban", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, clean corporate setting, formal attire", "Street-style portrait of a {gender}, gritty city background, bold outfit, high contrast lighting, strong pose, edgy aesthetic", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 17, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Fashion-inspired glamorous portrait with studio lighting and luxury feel", true, "glamour", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual everyday clothing", "Fashion-inspired portrait of a {gender} in glamorous makeup and clothing, studio lighting, soft glow effect, luxury editorial feel", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    
                    // Lifestyle & Identity-Focused Styles
                    { 18, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Scholar portrait with books or chalkboard in academic setting", true, "academic", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation", "Portrait of a {gender} scholar with books or chalkboard in background, glasses, thoughtful expression, classic academic setting and lighting", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 19, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Athletic portrait in workout gear with energetic expression", true, "fitness", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, formal business attire", "Athletic portrait of a {gender} in workout gear, gym or outdoor fitness location, strong pose, energetic expression, high contrast lighting", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) },
                    { 20, new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc), "Serene portrait in natural light with peaceful spiritual elements", true, "spiritual", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, busy commercial setting", "Serene portrait of a {gender} in natural light, peaceful outdoor or temple-like setting, soft expression, spiritual elements like beads or robes", new DateTime(2025, 6, 23, 12, 0, 0, 0, DateTimeKind.Utc) }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Remove custom styles
            migrationBuilder.DeleteData(
                table: "Styles",
                keyColumn: "Id",
                keyValues: new object[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 });

            // Restore original styles
            migrationBuilder.InsertData(
                table: "Styles",
                columns: new[] { "Id", "CreatedAt", "Description", "IsActive", "Name", "NegativePromptTemplate", "PromptTemplate", "UpdatedAt" },
                values: new object[,]
                {
                    { 1, new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7705), "Professional headshot with corporate styling", true, "professional", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual clothing, t-shirt, vacation setting, party scene, inappropriate attire", "{subject}, professional headshot, corporate portrait style, composition: centered subject with neutral background, slight angle, lighting: three-point studio lighting with soft key light, fill light, and rim light, color palette: muted blues and grays with natural skin tones, mood: confident and approachable, technical details: shot with 85mm lens at f/2.8, shallow depth of field, 4K resolution, additional elements: subtle office or gradient background, professional attire, well-groomed appearance", new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7705) },
                    { 2, new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7708), "Relaxed lifestyle portrait with natural styling", true, "casual", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation", "{subject}, casual lifestyle portrait, composition: rule of thirds with natural framing, lighting: golden hour natural sunlight with soft diffusion, color palette: warm earthy tones with vibrant accents, mood: relaxed, friendly and authentic, technical details: shot with 50mm lens at f/2.0, medium depth of field, additional elements: outdoor setting with natural elements, casual stylish clothing, genuine smile", new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7708) },
                    { 3, new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7710), "Artistic creative portrait with dynamic composition", true, "creative", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, boring, plain background, standard pose, conventional lighting", "{subject}, artistic creative portrait, composition: dynamic asymmetrical framing with creative negative space, lighting: dramatic side lighting with colored gels and intentional shadows, color palette: bold contrasting colors with artistic color grading, mood: intriguing and expressive, technical details: shot with wide angle lens, creative perspective, high contrast, additional elements: artistic background elements, creative props or styling, unique fashion elements", new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7710) },
                    { 4, new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7712), "Executive corporate portrait with formal styling", true, "corporate", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual attire, beach, party scene, inappropriate setting", "{subject}, executive corporate portrait, composition: formal centered composition with professional framing, lighting: classic Rembrandt lighting with soft fill, color palette: deep blues, grays and blacks with subtle accents, mood: authoritative, trustworthy and professional, technical details: shot with medium telephoto lens, optimal clarity and sharpness, additional elements: elegant business attire, office or branded environment subtly visible, power posture", new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7712) },
                    { 5, new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7714), "Optimized LinkedIn profile photo with professional appeal", true, "linkedin", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, full body shot, distracting background, extreme filters, unprofessional setting", "{subject}, optimized LinkedIn profile photo, composition: head and shoulders framing with balanced negative space above head, lighting: flattering soft light with subtle highlighting, color palette: professional neutral tones with complementary background, mood: approachable yet professional, technical details: 1000x1000 pixel square format, sharp focus on eyes, additional elements: simple clean background, professional but approachable expression, business casual attire", new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7714) },
                    { 6, new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7716), "Scholarly academic portrait with intellectual elements", true, "academic", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation", "{subject}, scholarly academic portrait, composition: dignified framing with intellectual elements, lighting: soft even lighting with subtle gradient, color palette: rich traditional tones with subtle depth, mood: thoughtful, knowledgeable and authoritative, technical details: medium format quality, excellent clarity, additional elements: books, laboratory or campus environment, academic attire or professional clothing, scholarly posture", new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7716) },
                    { 7, new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7718), "Modern tech industry portrait with contemporary styling", true, "tech", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, outdated technology, traditional office, formal suit", "{subject}, modern tech industry portrait, composition: contemporary framing with technical elements, lighting: modern high-key lighting with subtle blue accents, color palette: tech blues and cool grays with vibrant accents, mood: innovative, forward-thinking and approachable, technical details: ultra-high definition, perfect clarity, additional elements: minimal tech environment, modern casual professional attire, confident engaged expression", new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7718) },
                    { 8, new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7720), "Healthcare professional portrait with trustworthy appeal", true, "medical", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, inappropriate medical setting, casual vacation clothing", "{subject}, healthcare professional portrait, composition: trustworthy frontal composition with medical context, lighting: clean even lighting with healthy glow, color palette: whites, blues and comforting tones, mood: compassionate, competent and reassuring, technical details: sharp focus throughout, excellent clarity, additional elements: medical attire or lab coat, stethoscope or medical environment, caring expression", new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(7720) },
                    { 9, new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(8848), "Legal professional portrait with authoritative presence", true, "legal", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual setting, inappropriate attire, party scene", "{subject}, legal professional portrait, composition: balanced formal composition with legal elements, lighting: classical portrait lighting with defined shadows, color palette: deep rich tones with mahogany and navy accents, mood: authoritative, trustworthy and dignified, technical details: perfect focus and formal composition, additional elements: legal books, office with wooden elements, formal suit, confident and serious expression", new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(8849) },
                    { 10, new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(8851), "Premium executive portrait with commanding presence", true, "executive", "deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers, deformed, distorted, disfigured, poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, blurry, amputation, casual clothing, unprofessional setting, low quality office", "{subject}, premium executive portrait, composition: powerful centered composition with prestigious elements, lighting: dramatic executive lighting with defined highlights, color palette: luxury tones with gold, navy and charcoal accents, mood: powerful, successful and commanding, technical details: medium format quality with perfect detail rendering, additional elements: luxury office environment, premium suit or executive attire, leadership pose and expression", new DateTime(2025, 6, 10, 11, 38, 41, 286, DateTimeKind.Utc).AddTicks(8851) }
                });
        }
    }
}