export const environment = {
  production: true,
  apiUrl: 'http://localhost:5032/api',
  baseUrl: 'http://localhost:5032',
  name: 'docker-local',
  turnstileSiteKey: '',
  analytics: {
    ga4MeasurementId: 'G-FYQMYY2PJD',
  },
  features: {
    debugMode: false,
    useProxy: false,
    cors: true,
    enableImageValidation: true,
    enableReplicateCredits: false,
    openAIHeadshotMvp: true,
    profilePhotoWorkflowOverhaul: true,
    outcomePackagesVisible: true,
    profilePhotoScoreVisible: true,
    creativeStylePackVisible: true,
    premiumAugmentationsVisible: true,
    replicateTrainingFlowVisible: false,
    logging: {
      enableApiDebug: false,
      enableStateDebug: false,
      enableWorkflowDebug: false,
      enableAuthDebug: false,
      enableFileDebug: false,
      enableGalleryDebug: false,
      enableDashboardDebug: false,
    },
  },
  ngrok: {
    enabled: false,
    frontendUrl: 'http://localhost:4200',
    backendUrl: 'http://localhost:5032',
  },
  azure: {
    enabled: true,
    storageUrl: 'https://aipmstv16j74jubocuukg.blob.core.windows.net',
    stylePreviewUrl: 'https://aipmstv16j74jubocuukg.blob.core.windows.net',
  },
};
